### ISSUE TITLE
chore: webhooks 2.0 migration

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/gilgamesh#44]
Will follow steps from [here](https://docs.google.com/document/d/16jjoIiOXhCrdBrXZsvYeGKtGbk_X_paucOb5WNuIT9k/edit#heading=h.8xrq0xlr6rsm).

```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/gilgamesh/issues/46
- [x] chore: implement webhooks 2.0
- [ ] chore: implement JS client updates
- [ ] chore: implement tests
```

**Comment by chris13524** [comment]
Closing in-favor of https://github.com/WalletConnect/archive/issues/1
